[NUV-10242] Aggiornamento dipendenze per Symfony 5
madisoft/APYDataGridBundle pull request #13
Opened 2020-06-29 13:25 UTC by dborsatto

https://madisoft.atlassian.net/browse/NUV-10242

Con l'occasione, avevo concordato con Nicola di rimuovere le dipendenze di Mongo visto che questo è l'unico pacchetto a causarne l'installazione (e non viene nemmeno usato)

2020-06-29 13:25 UTC, dborsatto commented on Grid/Column/Column.php
> +        if ($this->hasDQLFunction()) {
Ho impostato le dipendenze a partire dalla 2.6 per cui questo controllo non serviva più.

2020-06-29 13:27 UTC, dborsatto commented on Grid/Grid.php
> +            [$columnId, $columnOrder] = explode('|', $order);
Questa modifica e la semplificazione degli if le ha fatte PHPStorm in automatico :thinking:

2020-07-27 15:00 UTC, nicolafo requested changes
Ti segno qui alcune deprecazioni rimaste:
- ColumnTitleAnnotationTranslationExtractor riga 87 -> \Twig_Node
- Export riga 462 -> \Twig_Template
- Grid riga 1831 -> \Twig_Template

2020-07-27 15:00 UTC, nicolafo commented on Twig/DataGridExtension.php
> +            new TwigFunction('grid_pager', [$this, 'getGridPager'], [
Il metodo getGridPager è stato eliminato, dovrebbe esserlo anche la funzione twig. Attenzione che è utilizzata in alcuni template interni al bundle (grid.html.twig, gridDialog.html.twig)

2020-07-28 09:38 UTC, nicolafo approved these changes

2020-07-28 09:39 UTC, merged